In [1]:
import pandas as pd
import csv
import requests
from io import StringIO

In [2]:
url = "https://aplicacoes.mds.gov.br/sagi/servicos/misocial/"
params = {
    "fq": ["anomes_s:2026*", "valor_repassado_bolsa_familia_s:*"],
    "fl": "codigo_ibge,anomes_s,qtd_familias_beneficiarias_bolsa_familia_s,valor_repassado_bolsa_familia_s,pbf_vlr_medio_benef_f",
    "q": "*:*",
    "rows": 100000,
    "sort": "anomes_s desc, codigo_ibge asc",
    "wt": "csv"
}

In [3]:
response = requests.get(url, params=params)

In [4]:
response.raise_for_status()

In [5]:
csv_data = StringIO(response.text)
reader = csv.DictReader(csv_data)

In [6]:
for i, row in enumerate(reader):
    if i< 10:
        print(row)

{'codigo_ibge': '110001', 'anomes_s': '202606', 'qtd_familias_beneficiarias_bolsa_familia_s': '1480', 'valor_repassado_bolsa_familia_s': '1012471', 'pbf_vlr_medio_benef_f': '688.76'}
{'codigo_ibge': '110002', 'anomes_s': '202606', 'qtd_familias_beneficiarias_bolsa_familia_s': '7697', 'valor_repassado_bolsa_familia_s': '5235744', 'pbf_vlr_medio_benef_f': '684.05'}
{'codigo_ibge': '110003', 'anomes_s': '202606', 'qtd_familias_beneficiarias_bolsa_familia_s': '340', 'valor_repassado_bolsa_familia_s': '238696', 'pbf_vlr_medio_benef_f': '702.05'}
{'codigo_ibge': '110004', 'anomes_s': '202606', 'qtd_familias_beneficiarias_bolsa_familia_s': '5591', 'valor_repassado_bolsa_familia_s': '3709872', 'pbf_vlr_medio_benef_f': '663.9'}
{'codigo_ibge': '110005', 'anomes_s': '202606', 'qtd_familias_beneficiarias_bolsa_familia_s': '1068', 'valor_repassado_bolsa_familia_s': '731043', 'pbf_vlr_medio_benef_f': '684.5'}
{'codigo_ibge': '110006', 'anomes_s': '202606', 'qtd_familias_beneficiarias_bolsa_familia_s': '415', 'valor_repassado_bolsa_familia_s': '276460', 'pbf_vlr_medio_benef_f': '666.17'}
{'codigo_ibge': '110007', 'anomes_s': '202606', 'qtd_familias_beneficiarias_bolsa_familia_s': '265', 'valor_repassado_bolsa_familia_s': '181167', 'pbf_vlr_medio_benef_f': '683.65'}
{'codigo_ibge': '110008', 'anomes_s': '202606', 'qtd_familias_beneficiarias_bolsa_familia_s': '1815', 'valor_repassado_bolsa_familia_s': '1261448', 'pbf_vlr_medio_benef_f': '695.78'}
{'codigo_ibge': '110009', 'anomes_s': '202606', 'qtd_familias_beneficiarias_bolsa_familia_s': '1092', 'valor_repassado_bolsa_familia_s': '687785', 'pbf_vlr_medio_benef_f': '631.57'}
{'codigo_ibge': '110010', 'anomes_s': '202606', 'qtd_familias_beneficiarias_bolsa_familia_s': '5152', 'valor_repassado_bolsa_familia_s': '3880091', 'pbf_vlr_medio_benef_f': '753.85'}

In [7]:
dados_pbf_2026 = pd.read_csv(StringIO(response.text))

In [8]:
ano = 2025
url = "https://aplicacoes.mds.gov.br/sagi/servicos/misocial/"
params = {
    "fq": [f"anomes_s:{ano}*", "valor_repassado_bolsa_familia_s:*"],
    "fl": "codigo_ibge,anomes_s,qtd_familias_beneficiarias_bolsa_familia_s,valor_repassado_bolsa_familia_s,pbf_vlr_medio_benef_f",
    "q": "*:*",
    "rows": 100000,
    "sort": "anomes_s desc, codigo_ibge asc",
    "wt": "csv"
}

In [9]:
r1  = requests.get(url = url, params = params)

In [10]:
r1.raise_for_status

In [11]:
c1 = StringIO(r1.text)
reader = csv.DictReader(c1)

In [12]:
dados_pbf_2025 = pd.read_csv(StringIO(r1.text))

In [13]:
dados_pbf = pd.concat([dados_pbf_2026, dados_pbf_2025],ignore_index=True)

In [14]:
dados_pbf['anomes_s'].unique()

array([202606, 202605, 202604, 202603, 202602, 202601, 202512, 202511,
       202510, 202509, 202508, 202507, 202506, 202505, 202504, 202503,
       202502, 202501])

In [15]:
ano = 2024
url = "https://aplicacoes.mds.gov.br/sagi/servicos/misocial/"
params = {
    "fq": [f"anomes_s:{ano}*", "valor_repassado_bolsa_familia_s:*"],
    "fl": "codigo_ibge,anomes_s,qtd_familias_beneficiarias_bolsa_familia_s,valor_repassado_bolsa_familia_s,pbf_vlr_medio_benef_f",
    "q": "*:*",
    "rows": 100000,
    "sort": "anomes_s desc, codigo_ibge asc",
    "wt": "csv"
}

In [16]:
r2 = requests.get(url   = url, params = params)

In [17]:
r2.raise_for_status

In [18]:
c2 = StringIO(r2.text)
reader = csv.DictReader(c2)

In [19]:
dados_pbf_2024 = pd.read_csv(StringIO(r2.text))

In [20]:
dados_pbf = pd.concat([dados_pbf,dados_pbf_2024],ignore_index = True)

In [21]:
dados_pbf['anomes_s'].unique()

array([202606, 202605, 202604, 202603, 202602, 202601, 202512, 202511,
       202510, 202509, 202508, 202507, 202506, 202505, 202504, 202503,
       202502, 202501, 202412, 202411, 202410, 202409, 202408, 202407,
       202406, 202405, 202404, 202403, 202402, 202401])

In [22]:
ano = 2023
url = "https://aplicacoes.mds.gov.br/sagi/servicos/misocial/"
params = {
    "fq": [f"anomes_s:{ano}*", "valor_repassado_bolsa_familia_s:*"],
    "fl": "codigo_ibge,anomes_s,qtd_familias_beneficiarias_bolsa_familia_s,valor_repassado_bolsa_familia_s,pbf_vlr_medio_benef_f",
    "q": "*:*",
    "rows": 100000,
    "sort": "anomes_s desc, codigo_ibge asc",
    "wt": "csv"
}

In [23]:
r3 = requests.get(url   = url, params = params)

In [24]:
r3.raise_for_status

In [25]:
c3 = StringIO(r3.text)
reader = csv.DictReader(c3)

In [26]:
dados_pbf_2023 = pd.read_csv(StringIO(r3.text))

In [27]:
dados_pbf = pd.concat([dados_pbf,dados_pbf_2023],ignore_index=True)

In [28]:
dados_pbf['anomes_s'].unique()

array([202606, 202605, 202604, 202603, 202602, 202601, 202512, 202511,
       202510, 202509, 202508, 202507, 202506, 202505, 202504, 202503,
       202502, 202501, 202412, 202411, 202410, 202409, 202408, 202407,
       202406, 202405, 202404, 202403, 202402, 202401, 202312, 202311,
       202310, 202309, 202308, 202307, 202306, 202305, 202304, 202303])

In [32]:
ano = 2021
url = "https://aplicacoes.mds.gov.br/sagi/servicos/misocial/"
params = {
    "fq": [f"anomes_s:{ano}*", "valor_repassado_bolsa_familia_s:*"],
    "fl": "codigo_ibge,anomes_s,qtd_familias_beneficiarias_bolsa_familia_s,valor_repassado_bolsa_familia_s,pbf_vlr_medio_benef_f",
    "q": "*:*",
    "rows": 100000,
    "sort": "anomes_s desc, codigo_ibge asc",
    "wt": "csv"
}

In [33]:
r4 = requests.get(url,params)

In [31]:
r4.raise_for_status()

In [34]:
dados_pbf_2021 = pd.read_csv(StringIO(r4.text))

In [35]:
dados_pbf_2021

,codigo_ibge,anomes_s,qtd_familias_beneficiarias_bolsa_familia_s,valor_repassado_bolsa_familia_s,pbf_vlr_medio_benef_f
0,110001,202110,1542,68238,44.25
1,110002,202110,4593,259791,56.56
2,110003,202110,221,11632,52.63
3,110004,202110,3654,302956,82.91
4,110005,202110,749,28276,37.75
...,...,...,...,...,...
55695,522200,202101,387,64878,167.64
55696,522205,202101,788,121883,154.67
55697,522220,202101,553,89346,161.57
55698,522230,202101,527,75888,144.00
55699,530010,202101,83665,15207244,181.76

In [37]:
dados_pbf = pd.concat([dados_pbf,dados_pbf_2021],ignore_index=True)

In [38]:
dados_pbf['anomes_s'].unique()

array([202606, 202605, 202604, 202603, 202602, 202601, 202512, 202511,
       202510, 202509, 202508, 202507, 202506, 202505, 202504, 202503,
       202502, 202501, 202412, 202411, 202410, 202409, 202408, 202407,
       202406, 202405, 202404, 202403, 202402, 202401, 202312, 202311,
       202310, 202309, 202308, 202307, 202306, 202305, 202304, 202303,
       202110, 202109, 202108, 202107, 202106, 202105, 202104, 202103,
       202102, 202101])

In [39]:
ano = 2020
url = "https://aplicacoes.mds.gov.br/sagi/servicos/misocial/"
params = {
    "fq": [f"anomes_s:{ano}*", "valor_repassado_bolsa_familia_s:*"],
    "fl": "codigo_ibge,anomes_s,qtd_familias_beneficiarias_bolsa_familia_s,valor_repassado_bolsa_familia_s,pbf_vlr_medio_benef_f",
    "q": "*:*",
    "rows": 100000,
    "sort": "anomes_s desc, codigo_ibge asc",
    "wt": "csv"
}

In [40]:
r5 = requests.get(url,params)

In [41]:
r5.raise_for_status()

In [42]:
dados_pbf_2020 = pd.read_csv(StringIO(r5.text))

In [43]:
dados_pbf_2020

,codigo_ibge,anomes_s,qtd_familias_beneficiarias_bolsa_familia_s,valor_repassado_bolsa_familia_s,pbf_vlr_medio_benef_f
0,110001,202012,1524,19051.0,12.50
1,110002,202012,3938,80605.0,20.47
2,110003,202012,187,1995.0,10.67
3,110004,202012,3132,100047.0,31.94
4,110005,202012,711,8805.0,12.38
...,...,...,...,...,...
66835,522200,202001,357,55295.0,154.89
66836,522205,202001,809,125263.0,154.84
66837,522220,202001,489,78809.0,161.16
66838,522230,202001,491,69187.0,140.91
66839,530010,202001,66439,12109549.0,182.27

In [44]:
dados_pbf = pd.concat([dados_pbf,dados_pbf_2020],ignore_index=True)

In [45]:
dados_pbf['anomes_s'].unique()

array([202606, 202605, 202604, 202603, 202602, 202601, 202512, 202511,
       202510, 202509, 202508, 202507, 202506, 202505, 202504, 202503,
       202502, 202501, 202412, 202411, 202410, 202409, 202408, 202407,
       202406, 202405, 202404, 202403, 202402, 202401, 202312, 202311,
       202310, 202309, 202308, 202307, 202306, 202305, 202304, 202303,
       202110, 202109, 202108, 202107, 202106, 202105, 202104, 202103,
       202102, 202101, 202012, 202011, 202010, 202009, 202008, 202007,
       202006, 202005, 202004, 202003, 202002, 202001])

In [47]:
ano = 2019
url = "https://aplicacoes.mds.gov.br/sagi/servicos/misocial/"
params = {
    "fq": [f"anomes_s:{ano}*", "valor_repassado_bolsa_familia_s:*"],
    "fl": "codigo_ibge,anomes_s,qtd_familias_beneficiarias_bolsa_familia_s,valor_repassado_bolsa_familia_s,pbf_vlr_medio_benef_f",
    "q": "*:*",
    "rows": 100000,
    "sort": "anomes_s desc, codigo_ibge asc",
    "wt": "csv"
}

In [48]:
r6 = requests.get(url,params)

In [49]:
r6.raise_for_status

In [50]:
dados_pbf_2019 = pd.read_csv(StringIO(r6.text))

In [51]:
dados_pbf_2019.rename(columns={"ibge": "codigo_ibge", "anomes": "anomes_s", "qtd_familias_beneficiarias_bolsa_familia": "qtd_familias_beneficiarias_bolsa_familia_s", "valor_repassado_bolsa_familia": "valor_repassado_bolsa_familia_s"}, inplace=True)

In [52]:
dados_pbf_2019

,codigo_ibge,anomes_s,qtd_familias_beneficiarias_bolsa_familia_s,valor_repassado_bolsa_familia_s,pbf_vlr_medio_benef_f
0,110001,201912,1409,219710.0,155.93
1,110002,201912,3343,491956.0,147.16
2,110003,201912,159,23483.0,147.69
3,110004,201912,2380,382892.0,160.88
4,110005,201912,613,94495.0,154.15
...,...,...,...,...,...
66835,522200,201901,351,56384.0,160.64
66836,522205,201901,842,132604.0,157.49
66837,522220,201901,579,91913.0,158.74
66838,522230,201901,549,79253.0,144.36
66839,530010,201901,68892,12013474.0,174.38

In [53]:
dados_pbf = pd.concat([dados_pbf,dados_pbf_2019],ignore_index=True)

In [54]:
ano = 2018
url = "https://aplicacoes.mds.gov.br/sagi/servicos/misocial/"
params = {
    "fq": [f"anomes_s:{ano}*", "valor_repassado_bolsa_familia_s:*"],
    "fl": "codigo_ibge,anomes_s,qtd_familias_beneficiarias_bolsa_familia_s,valor_repassado_bolsa_familia_s,pbf_vlr_medio_benef_f",
    "q": "*:*",
    "rows": 100000,
    "sort": "anomes_s desc, codigo_ibge asc",
    "wt": "csv"
}

In [55]:
r7 = requests.get(url,params)

In [56]:
r7.raise_for_status

In [58]:
dados_pbf_2018 = pd.read_csv(StringIO(r7.text))

In [59]:
dados_pbf_2018

,codigo_ibge,anomes_s,qtd_familias_beneficiarias_bolsa_familia_s,valor_repassado_bolsa_familia_s,pbf_vlr_medio_benef_f
0,110001,201812,1498,235579,157.26
1,110002,201812,3964,586759,148.02
2,110003,201812,187,27207,145.49
3,110004,201812,2671,404826,151.56
4,110005,201812,668,99256,148.59
...,...,...,...,...,...
66835,522200,201801,489,72543,148.35
66836,522205,201801,805,136236,169.24
66837,522220,201801,665,101439,152.54
66838,522230,201801,623,91149,146.31
66839,530010,201801,80959,12984317,160.38

In [61]:
dados_pbf_2018.rename(columns={"ibge": "codigo_ibge", "anomes": "anomes_s", "qtd_familias_beneficiarias_bolsa_familia": "qtd_familias_beneficiarias_bolsa_familia_s", "valor_repassado_bolsa_familia": "valor_repassado_bolsa_familia_s"}, inplace=True)

In [62]:
dados_pbf = pd.concat([dados_pbf,dados_pbf_2018],ignore_index = True)

In [64]:
dados_pbf['anomes_s'].unique()

array([202606, 202605, 202604, 202603, 202602, 202601, 202512, 202511,
       202510, 202509, 202508, 202507, 202506, 202505, 202504, 202503,
       202502, 202501, 202412, 202411, 202410, 202409, 202408, 202407,
       202406, 202405, 202404, 202403, 202402, 202401, 202312, 202311,
       202310, 202309, 202308, 202307, 202306, 202305, 202304, 202303,
       202110, 202109, 202108, 202107, 202106, 202105, 202104, 202103,
       202102, 202101, 202012, 202011, 202010, 202009, 202008, 202007,
       202006, 202005, 202004, 202003, 202002, 202001, 201912, 201911,
       201910, 201909, 201908, 201907, 201906, 201905, 201904, 201903,
       201902, 201901, 201812, 201811, 201810, 201809, 201808, 201807,
       201806, 201805, 201804, 201803, 201802, 201801])

In [63]:
ano = 2017
url = "https://aplicacoes.mds.gov.br/sagi/servicos/misocial/"
params = {
    "fq": [f"anomes_s:{ano}*", "valor_repassado_bolsa_familia_s:*"],
    "fl": "codigo_ibge,anomes_s,qtd_familias_beneficiarias_bolsa_familia_s,valor_repassado_bolsa_familia_s,pbf_vlr_medio_benef_f",
    "q": "*:*",
    "rows": 100000,
    "sort": "anomes_s desc, codigo_ibge asc",
    "wt": "csv"
}

In [65]:
r8 = requests.get(url,params)

In [66]:
r8.raise_for_status

In [67]:
dados_pbf_2017 = pd.read_csv(StringIO(r8.text))

In [68]:
dados_pbf_2017

,codigo_ibge,anomes_s,qtd_familias_beneficiarias_bolsa_familia_s,valor_repassado_bolsa_familia_s,pbf_vlr_medio_benef_f
0,110001,201712,1568,247946,158.13
1,110002,201712,4150,588255,141.75
2,110003,201712,214,28833,134.73
3,110004,201712,2482,336757,135.68
4,110005,201712,667,99488,149.16
...,...,...,...,...,...
66835,522200,201701,557,80735,144.95
66836,522205,201701,585,101854,174.11
66837,522220,201701,614,95830,156.07
66838,522230,201701,577,89662,155.39
66839,530010,201701,82213,12683244,154.27

In [69]:
dados_pbf = pd.concat([dados_pbf,dados_pbf_2017],ignore_index = True)

In [70]:
ano = 2016
url = "https://aplicacoes.mds.gov.br/sagi/servicos/misocial/"
params = {
    "fq": [f"anomes_s:{ano}*", "valor_repassado_bolsa_familia_s:*"],
    "fl": "codigo_ibge,anomes_s,qtd_familias_beneficiarias_bolsa_familia_s,valor_repassado_bolsa_familia_s,pbf_vlr_medio_benef_f",
    "q": "*:*",
    "rows": 100000,
    "sort": "anomes_s desc, codigo_ibge asc",
    "wt": "csv"
}

In [71]:
r9 = requests.get(url,params)

In [72]:
r9.raise_for_status

In [73]:
dados_pbf_2016 = pd.read_csv(StringIO(r9.text))

In [74]:
dados_pbf_2016

,codigo_ibge,anomes_s,qtd_familias_beneficiarias_bolsa_familia_s,valor_repassado_bolsa_familia_s,pbf_vlr_medio_benef_f
0,110001,201612,1682,283447.0,168.52
1,110002,201612,4489,635241.0,141.51
2,110003,201612,259,33882.0,130.82
3,110004,201612,3009,392798.0,130.54
4,110005,201612,788,115941.0,147.13
...,...,...,...,...,...
66835,522200,201601,660,93212.0,141.23
66836,522205,201601,574,89955.0,156.72
66837,522220,201601,546,77298.0,141.57
66838,522230,201601,608,87192.0,143.41
66839,530010,201601,85171,11923719.0,140.00

In [75]:
dados_pbf = pd.concat([dados_pbf,dados_pbf_2016],ignore_index=True)

In [76]:
ano = 2015
url = "https://aplicacoes.mds.gov.br/sagi/servicos/misocial/"
params = {
    "fq": [f"anomes_s:{ano}*", "valor_repassado_bolsa_familia_s:*"],
    "fl": "codigo_ibge,anomes_s,qtd_familias_beneficiarias_bolsa_familia_s,valor_repassado_bolsa_familia_s,pbf_vlr_medio_benef_f",
    "q": "*:*",
    "rows": 100000,
    "sort": "anomes_s desc, codigo_ibge asc",
    "wt": "csv"
}

In [77]:
r10 = requests.get(url,params)

In [78]:
r10.raise_for_status

In [79]:
dados_pbf_2015 = pd.read_csv(StringIO(r10.text))

In [80]:
dados_pbf_2015

,codigo_ibge,anomes_s,qtd_familias_beneficiarias_bolsa_familia_s,valor_repassado_bolsa_familia_s,pbf_vlr_medio_benef_f
0,110001,201512,1861,284016,152.61
1,110002,201512,5204,712945,137.00
2,110003,201512,395,51895,131.38
3,110004,201512,3683,488225,132.56
4,110005,201512,876,119131,135.99
...,...,...,...,...,...
66835,522200,201501,743,106992,144.00
66836,522205,201501,546,84411,154.60
66837,522220,201501,603,88131,146.15
66838,522230,201501,634,101396,159.93
66839,530010,201501,86281,12387614,143.57

In [81]:
dados_pbf = pd.concat([dados_pbf,dados_pbf_2015],ignore_index=True)

In [83]:
dados_pbf['anomes_s'].unique()

array([202606, 202605, 202604, 202603, 202602, 202601, 202512, 202511,
       202510, 202509, 202508, 202507, 202506, 202505, 202504, 202503,
       202502, 202501, 202412, 202411, 202410, 202409, 202408, 202407,
       202406, 202405, 202404, 202403, 202402, 202401, 202312, 202311,
       202310, 202309, 202308, 202307, 202306, 202305, 202304, 202303,
       202110, 202109, 202108, 202107, 202106, 202105, 202104, 202103,
       202102, 202101, 202012, 202011, 202010, 202009, 202008, 202007,
       202006, 202005, 202004, 202003, 202002, 202001, 201912, 201911,
       201910, 201909, 201908, 201907, 201906, 201905, 201904, 201903,
       201902, 201901, 201812, 201811, 201810, 201809, 201808, 201807,
       201806, 201805, 201804, 201803, 201802, 201801, 201712, 201711,
       201710, 201709, 201708, 201707, 201706, 201705, 201704, 201703,
       201702, 201701, 201612, 201611, 201610, 201609, 201608, 201607,
       201606, 201605, 201604, 201603, 201602, 201601, 201512, 201511,
       201510, 201509, 201508, 201507, 201506, 201505, 201504, 201503,
       201502, 201501])

In [84]:
ano = 2014
url = "https://aplicacoes.mds.gov.br/sagi/servicos/misocial/"
params = {
    "fq": [f"anomes_s:{ano}*", "valor_repassado_bolsa_familia_s:*"],
    "fl": "codigo_ibge,anomes_s,qtd_familias_beneficiarias_bolsa_familia_s,valor_repassado_bolsa_familia_s,pbf_vlr_medio_benef_f",
    "q": "*:*",
    "rows": 100000,
    "sort": "anomes_s desc, codigo_ibge asc",
    "wt": "csv"
}

In [85]:
r11 = requests.get(url,params)

In [86]:
r11.raise_for_status

In [87]:
dados_pbf_2014 = pd.read_csv(StringIO(r11.text))

In [88]:
dados_pbf_2014

,codigo_ibge,anomes_s,qtd_familias_beneficiarias_bolsa_familia_s,valor_repassado_bolsa_familia_s,pbf_vlr_medio_benef_f
0,110001,201412,2095,336204,160.48
1,110002,201412,5532,858037,155.10
2,110003,201412,404,54688,135.37
3,110004,201412,4011,570551,142.25
4,110005,201412,789,109212,138.42
...,...,...,...,...,...
66833,522200,201401,696,89420,128.48
66834,522205,201401,581,76182,131.12
66835,522220,201401,581,78590,135.27
66836,522230,201401,560,85946,153.48
66837,530010,201401,93365,11764168,126.00

In [89]:
dados_pbf = pd.concat([dados_pbf,dados_pbf_2014],ignore_index=True)

In [90]:
dados_pbf

,codigo_ibge,anomes_s,qtd_familias_beneficiarias_bolsa_familia_s,valor_repassado_bolsa_familia_s,pbf_vlr_medio_benef_f
0,110001,202606,1480,1012471.0,688.76
1,110002,202606,7697,5235744.0,684.05
2,110003,202606,340,238696.0,702.05
3,110004,202606,5591,3709872.0,663.90
4,110005,202606,1068,731043.0,684.50
...,...,...,...,...,...
746381,522200,201401,696,89420.0,128.48
746382,522205,201401,581,76182.0,131.12
746383,522220,201401,581,78590.0,135.27
746384,522230,201401,560,85946.0,153.48
746385,530010,201401,93365,11764168.0,126.00

In [91]:
ano = 2013
url = "https://aplicacoes.mds.gov.br/sagi/servicos/misocial/"
params = {
    "fq": [f"anomes_s:{ano}*", "valor_repassado_bolsa_familia_s:*"],
    "fl": "codigo_ibge,anomes_s,qtd_familias_beneficiarias_bolsa_familia_s,valor_repassado_bolsa_familia_s,pbf_vlr_medio_benef_f",
    "q": "*:*",
    "rows": 100000,
    "sort": "anomes_s desc, codigo_ibge asc",
    "wt": "csv"
}

In [92]:
r12 = requests.get(url,params)

In [93]:
r12.raise_for_status

In [94]:
dados_pbf_2013 = pd.read_csv(StringIO(r12.text))

In [95]:
dados_pbf_2013

,codigo_ibge,anomes_s,qtd_familias_beneficiarias_bolsa_familia_s,valor_repassado_bolsa_familia_s,pbf_vlr_medio_benef_f
0,110001,201312,2114,303526,143.58
1,110002,201312,6100,858214,140.69
2,110003,201312,518,64278,124.09
3,110004,201312,4794,616966,128.70
4,110005,201312,1094,140690,128.60
...,...,...,...,...,...
66783,522200,201301,838,105786,126.24
66784,522205,201301,630,78944,125.31
66785,522220,201301,600,77468,129.11
66786,522230,201301,487,78384,160.95
66787,530010,201301,94902,11450358,120.65

In [96]:
dados_pbf = pd.concat([dados_pbf,dados_pbf_2013],ignore_index=True)

In [98]:
ano = 2012
url = "https://aplicacoes.mds.gov.br/sagi/servicos/misocial/"
params = {
    "fq": [f"anomes_s:{ano}*", "valor_repassado_bolsa_familia_s:*"],
    "fl": "codigo_ibge,anomes_s,qtd_familias_beneficiarias_bolsa_familia_s,valor_repassado_bolsa_familia_s,pbf_vlr_medio_benef_f",
    "q": "*:*",
    "rows": 100000,
    "sort": "anomes_s desc, codigo_ibge asc",
    "wt": "csv"
}

In [99]:
r13 = requests.get(url,params)

In [100]:
r13.raise_for_status

In [101]:
dados_pbf_2012 = pd.read_csv(StringIO(r13.text))

In [102]:
dados_pbf_2012

,codigo_ibge,anomes_s,qtd_familias_beneficiarias_bolsa_familia_s,valor_repassado_bolsa_familia_s,pbf_vlr_medio_benef_f
0,110001,201212,2089,287070,137.42
1,110002,201212,5294,728846,137.67
2,110003,201212,565,77648,137.43
3,110004,201212,5519,731544,132.55
4,110005,201212,1158,150636,130.08
...,...,...,...,...,...
66775,522200,201201,860,88840,103.30
66776,522205,201201,532,61412,115.44
66777,522220,201201,559,71622,128.13
66778,522230,201201,502,55572,110.70
66779,530010,201201,73963,7273962,98.35

In [103]:
dados_pbf = pd.concat([dados_pbf,dados_pbf_2012],ignore_index=True)

In [104]:
ano = 2011
url = "https://aplicacoes.mds.gov.br/sagi/servicos/misocial/"
params = {
    "fq": [f"anomes_s:{ano}*", "valor_repassado_bolsa_familia_s:*"],
    "fl": "codigo_ibge,anomes_s,qtd_familias_beneficiarias_bolsa_familia_s,valor_repassado_bolsa_familia_s,pbf_vlr_medio_benef_f",
    "q": "*:*",
    "rows": 100000,
    "sort": "anomes_s desc, codigo_ibge asc",
    "wt": "csv"
}

In [105]:
r14 = requests.get(url,params)

In [106]:
r14.raise_for_status

In [107]:
dados_pbf_2011 = pd.read_csv(StringIO(r14.text))

In [108]:
dados_pbf_2011

,codigo_ibge,anomes_s,qtd_familias_beneficiarias_bolsa_familia_s,valor_repassado_bolsa_familia_s,pbf_vlr_medio_benef_f
0,110001,201112,1851,229284.0,123.87
1,110002,201112,4738,570550.0,120.42
2,110003,201112,537,60422.0,112.52
3,110004,201112,5549,667864.0,120.36
4,110005,201112,1131,130204.0,115.12
...,...,...,...,...,...
66775,522200,201101,820,63810.0,77.82
66776,522205,201101,550,50854.0,92.46
66777,522220,201101,493,50282.0,101.99
66778,522230,201101,525,47065.0,89.65
66779,530010,201101,98567,7509996.0,76.19

In [109]:
ano = 2010
url = "https://aplicacoes.mds.gov.br/sagi/servicos/misocial/"
params = {
    "fq": [f"anomes_s:{ano}*", "valor_repassado_bolsa_familia_s:*"],
    "fl": "codigo_ibge,anomes_s,qtd_familias_beneficiarias_bolsa_familia_s,valor_repassado_bolsa_familia_s,pbf_vlr_medio_benef_f",
    "q": "*:*",
    "rows": 100000,
    "sort": "anomes_s desc, codigo_ibge asc",
    "wt": "csv"
}

In [110]:
r15 = requests.get(url,params)

In [111]:
dados_pbf_2010 = pd.read_csv(StringIO(r15.text))